apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user-pod
  template:
    metadata:
      labels:
        app: backend-user-pod
    spec:
      containers:
        - name: udagram-api-user
          image: maerryham/udagram-api-user:v2
          ports:
          - containerPort: 8080
          command: ["sleep", "3600"]
          env:
          # Define the environment variable
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: postgres_db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: postgres_host
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: aws_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: aws_secret_access_key
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: aws_bucket
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt_secret
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: url