apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed-pod
  template:
    metadata:
      labels:
        app: backend-feed-pod
    spec:
      containers:
        - name: udagram-frontend
          image: maerryham/udagram-frontend:v6
          command: ["sleep", "3600"]
