apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy-pod
  template:
    metadata:
      labels:
        app: reverseproxy-pod
    spec:
      containers:
        - name: reverseproxy
          image: maerryham/reverseproxy:v1
          command: ["sleep", "3600"]
     