apiVersion: v1
kind: Secret
metadata:
  name: my-aws-secret
type: Opaque
data:
  aws_access_key_id: QUtJQVhEUEJWTUFZTzNJU0hNSDI=
  aws_secret_access_key: OXN2NFlwREJiUTdkRTBMQ1U2Z2xYSjV3U2VjNTNJVXZoSmk2OFZSRA==
  aws_profile: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBWERQQlZNQVlPM0lTSE1IMgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSA5c3Y0WXBEQmJRN2RFMExDVTZnbFhKNXdTZWM1M0lVdmhKaTY4VlJECg==
