apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed-pod
  name: backend-feed-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-feed-pod
  template:
    metadata:
      labels:
        service: backend-feed-pod
    spec:
      containers:
      - image: maerryham/udagram-api-feed:v2
        name: udagram-api-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8080
        command: ["sleep", "3600"]
        env:
          # Define the environment variable
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: postgres_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: postgres_db
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: postgres_host
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: aws_region
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: my-aws-secret
                key: aws_access_key_id
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-aws-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-aws-secret
                key: aws_secret_access_key
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: aws_bucket
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: jwt_secret
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: url
      restartPolicy: Always
