apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-pod
  name: frontend-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-pod
  template:
    metadata:
      labels:
        service: frontend-pod
    spec:
      containers:
      - image: maerryham/udagram-frontend:v8
        name: udagram-frontend
        imagePullPolicy: Always       
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        ports:
        - containerPort: 80
        command: ["sleep", "3600"]
      restartPolicy: Always
