apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy-pod
  name: reverseproxy-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy-pod
  template:
    metadata:
      labels:
        service: reverseproxy-pod
    spec:
      containers:
      - image: maerryham/reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"   
        ports:
        - containerPort: 8080
        command: ["sleep", "3600"]
      restartPolicy: Always
     